### ISSUE TITLE
New commands

### ISSUE THREAD

**Issue by tenhobi** [jakemac53/built_html#4]
We might consider to add some commends w/o parameters:

* [x] ~timestamp~
* [x] package version (if that is possible to fetch)

**Comment by jakemac53** [comment]
The `timestamp` one would cause a non-hermetic build so I don't want to do that one, but package version would totally be doable, we can read the pubspec.yaml.

**Comment by tenhobi** [comment]
OK. Any idea how to get the package version? Maybe by simple loading the file by ourselves?

**Comment by jakemac53** [comment]
We can read the `pubspec.yaml` with something like

```dart
var pubspecId = AssetId(buildStep.inputId.package, 'pubspec.yaml');
if (!await buildStep.canRead(pubspecId)) {
  logger.severe('Cannot read pubspec.yaml! Make sure it is included as a source in your target.');
  return;
}
var pubspec = await buildStep.readAsString(pubspecId);
```

And then use either the `pubspec_parse` package to parse the result or manually parse it with the `yaml` package and grab the version field.

Note that you can only read the pubspec.yaml for the root package (we don't expose anything outside of `lib` for packages you depend on), which is why I added in the canRead logic. It can also be unreadable if people have a custom default target for their app and don't include it.

**Comment by tenhobi** [comment]
I will add it to #6 later today. :-)

**Comment by jakemac53** [comment]
cool sounds good!
